workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: always

include:
  - project: products/aicloud/cicd
    ref: fix-test-functiona
    file: /gitlab-ci-mlspace-cli.yaml
